name: Java Build Pipeline CI/CD

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Select branch to build"
        required: true
        default: "main"
        type: string
      environment:
        description: "Select environment (dev, staging, prod)"
        required: true
        default: "dev"
        type: choice
        options:
          - main
          - dev
          - staging
          - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: prashant/dockerproject-2:latest

